INSERT OR REPLACE INTO farms (id, name, description) VALUES
('20', '🇳🇱 NL COFFEE SHOP 🇳🇱', 'Production CALITEK'),
('30', 'Cali top SHELF 🇺🇸', ''),
('34', 'Sahas Terps 🚀', ''),
('35', 'Wizzard Trees 🌳🪄', ''),
('36', '🦀 THE TEN CO 🦀', ''),
('37', 'Cali top SHELF distro 🇺🇸', ''),
('38', 'Mariposa Farmz 🦋', ''),
('39', 'POPEYE STATIC GROWER PSG FARMZ 🥚', ''),
('40', '🥫PSG FARMZ🥫', ''),
('41', 'Katrina Farmz usa 🇺🇸', ''),
('42', 'DISTRO 4A ++ 🇺🇸🧑‍💻', ''),
('43', 'CALI ALL BLACK FARMZ 🏴‍☠️', ''),
('44', 'HASHIVA FARMZ 🇺🇸🔵', ''),
('45', 'POPEYE STATIC GROWER Usa 🇺🇸🇺🇸🚀🚀🧑‍💻🧑‍💻 PSG FARMZ', ''),
('46', '👑KINKS FARMS 👑', ''),
('47', 'REGULAR EDITION ‼️‼️🦈', ''),
('48', 'CALI PLATES PREMIUM 🌞🌞🚀🚀🦈🇺🇸🇺🇸', ''),
('49', 'CALIPLATE PRENIUM STATIC 🖤', ''),
('50', 'CALIPLATE REGULAR EDIDTION ☑️', ''),
('51', 'SASUKER FARM 🇲🇦', ''),
('52', 'NO FARM 🇲🇦', '');