name = "griseldav3"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "griseldav3-db"
database_id = "VOTRE-DATABASE-ID-ICI"

[[r2_buckets]]
binding = "R2"
bucket_name = "griseldav3-media"