name = "calitekv3"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "griselda-db"
database_id = "9e675619-cc58-4056-9fb6-49e51f9778be"

[[r2_buckets]]
binding = "R2"
bucket_name = "griselda-media"
